// import localFont from "next/font/local";
// import "./globals.css";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Mv Councellor",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//       <div className="flex flex-col max-w-screen overflow-hidden" >
//         <div><Navbar/></div>
//         <div className="min-h-[70vh]">{children}</div>
//         <div><Footer/></div>
//       </div>
        
//       </body>
//     </html>
//   );
// }
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";


// Load custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Mv Councellor",
  description: "Generated by create next app",
};

// GoogleTranslate component to add the translator widget


export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Google Translate Widget */}
        <div className="flex flex-col max-w-screen overflow-hidden">
          <div ><Navbar /></div>
          <div className="min-h-[70vh]">{children}</div>
          <div><Footer /></div>
        </div>
        <Toaster/>
      </body>
    </html>
  );
}
