// import localFont from "next/font/local";
// import "./globals.css";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Mv Councellor",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//       <div className="flex flex-col max-w-screen overflow-hidden" >
//         <div><Navbar/></div>
//         <div className="min-h-[70vh]">{children}</div>
//         <div><Footer/></div>
//       </div>
        
//       </body>
//     </html>
//   );
// }

import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";
import "./globals.css";
// Load custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Mv Councellor",
//   description: "A platform for counseling and psychological help.",
// };


export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
    {/* <Head>
      <title>{metadata.title}</title>
      <meta name="description" content={metadata.description} />
      <meta property="og:title" content="Mv Councellor"/>
      <meta property="og:description" content="A platform for counseling and psychological help." />
      <meta property="og:image" content="/Logo.jpg"/> 
      <meta property="og:url" content="https://mv-councellor.vercel.app" />
      <meta property="og:type" content="website" />
    </Head> */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Google Translate Widget */}
        <div className="flex flex-col max-w-screen overflow-hidden">
          <div ><Navbar /></div>
          <div className="">{children}</div>
          <div><Footer /></div>
        </div>
        <Toaster/>
      </body>
    </html>
  );
}
